// challenges.ts

export const challenges = {
  toddlers: [
    // 50 retos para 3-4 años
    "Salta como una rana 5 veces.",
    "Haz el sonido de un león rugiendo muy fuerte.",
    "Camina como un pingüino por la habitación.",
    "Canta la canción de 'Estrellita dónde estás'.",
    "Tócate la nariz con el dedo índice.",
    "Gira en círculos 3 veces (¡con cuidado!).",
    "Haz como que estás durmiendo y ronca muy fuerte.",
    "Aplaude 10 veces.",
    "Busca algo en la habitación que sea de color rojo.",
    "Manda un beso volado a cada jugador.",
    "Gatea como un bebé hasta la puerta.",
    "Haz el sonido de una vaca (¡Muuuu!).",
    "Intenta pararte en un solo pie por 3 segundos.",
    "Baila tu canción favorita por 10 segundos.",
    "Esconde tu cara con las manos y di '¡Aquí estoy!'.",
    "Marcha como un soldado por la habitación.",
    "Haz como si nadaras en el agua.",
    "Tócate los pies sin doblar las rodillas.",
    "Haz el sonido de un pollito.",
    "Imita a un mono rascándote la cabeza.",
    "Abraza a la persona que está a tu derecha.",
    "Rueda como un tronco en el suelo.",
    "Camina de puntitas sin hacer ruido.",
    "Haz el sonido de un fantasma (¡Boooo!).",
    "Infla tus cachetes como un pez globo.",
    "Sacude todo tu cuerpo como un perro mojado.",
    "Haz cosquillas a tus propias rodillas.",
    "Siéntate en el suelo y levántate sin usar las manos.",
    "Haz una cara muy, muy triste.",
    "Ahora, haz una cara muy, muy feliz.",
    "Imita el sonido de la lluvia con tus dedos.",
    "Estírate tan alto como puedas, como si quisieras tocar el techo.",
    "Camina como un gigante, dando pasos muy grandes.",
    "Haz el sonido de un caballo.",
    "Da un aplauso muy suave y otro muy fuerte.",
    "Tócate la cabeza y después los hombros, 5 veces.",
    "Haz el sonido de una serpiente.",
    "Pon tus manos en la cintura y mueve las caderas en círculos.",
    "Imita a un gato estirándose.",
    "Haz como si estuvieras comiendo una sopa muy caliente.",
    "Sopla tan fuerte como si fueras a apagar las velas de un pastel.",
    "Esconde un objeto pequeño en tu mano y que los demás adivinen cuál es.",
    "Da tres pasos de gigante.",
    "Ahora, da diez pasos de hormiguita.",
    "Intenta hacer un sonido de motor de coche.",
    "Haz 'ojitos' tiernos para convencer a alguien de algo.",
    "Arruga la nariz como un conejo.",
    "Imita el llanto de un bebé.",
    "Di 'hola' con una voz muy grave y luego con una muy aguda.",
    "Lanza un beso al techo."
  ],
  kids: [
    // 50 retos para 5-12 años
    "Construye una torre usando 3 cojines del sillón.",
    "Dibuja un círculo en el aire con tu nariz.",
    "Baila como un robot que se está quedando sin baterías.",
    "Di un trabalenguas tres veces seguidas.",
    "Nombra 5 animales que vivan en la selva.",
    "Actúa como si fueras un superhéroe que acaba de salvar la ciudad.",
    "Camina de espaldas de una pared a otra.",
    "Inventa un saludo secreto y enséñaselo a otro jugador.",
    "Canta el 'Feliz Cumpleaños' con voz de ardilla.",
    "Haz 10 sentadillas lo más rápido que puedas.",
    "Cuenta un chiste (no importa si es bueno o malo).",
    "Actúa como si caminaras sobre la luna (en cámara lenta).",
    "Inventa un rap corto sobre tu comida favorita.",
    "Haz una imitación de tu profesor o profesora favorita.",
    "Narra los siguientes 2 turnos como si fueras un comentarista de fútbol.",
    "Intenta hacer malabares con dos pares de calcetines.",
    "Ponte un calcetín en la mano y haz que hable como una marioneta.",
    "Baila la Macarena.",
    "Haz tu mejor cara de 'selfie' y mantenla por 10 segundos.",
    "Crea un nuevo paso de baile y ponle un nombre.",
    "Actúa una escena de tu película favorita.",
    "Haz 15 'jumping jacks' (saltos de tijera).",
    "Describe lo que cenaste ayer sin usar la letra 'A'.",
    "Usa un control remoto como si fuera un teléfono y ten una conversación muy importante.",
    "Elige a otro jugador y dale un cumplido sincero.",
    "Habla como un pirata hasta tu próximo turno.",
    "Haz una estatua divertida y no te muevas hasta que todos adivinen qué eres.",
    "Lanza un par de calcetines a un bote o cesto desde 3 pasos de distancia.",
    "Mantén el equilibrio en un pie por 15 segundos.",
    "Corre en tu lugar tan rápido como puedas por 10 segundos.",
    "Imita a tu personaje de caricatura favorito.",
    "Intenta tocar tus hombros con las manos cruzadas por la espalda.",
    "Construye el fuerte más pequeño del mundo con tus manos.",
    "Haz mímica de tu deporte favorito para que los demás lo adivinen.",
    "Recita el abecedario al revés (o inténtalo).",
    "Salta la cuerda imaginaria por 20 segundos.",
    "Actúa como si el suelo fuera lava caliente.",
    "Inventa un hechizo mágico y explica qué hace.",
    "Hazle una pregunta a la persona de tu izquierda usando solo mímica.",
    "Con los ojos cerrados, intenta dibujar un cuadrado en el aire.",
    "Intenta reírte sin hacer ningún sonido por 10 segundos.",
    "Nombra 3 cosas que encuentres en una playa.",
    "Haz el sonido de un despertador.",
    "Camina por la habitación con los ojos de un detective buscando pistas.",
    "Inventa una palabra nueva y define qué significa.",
    "Haz 5 'burpees' (o tu mejor intento).",
    "Canta el coro de una canción, pero reemplaza todas las vocales con la letra 'i'.",
    "Actúa como si estuvieras probando una comida que no te gusta nada.",
    "Intenta tararear una canción para que los demás la adivinen.",
    "Da la vuelta a la mesa principal corriendo en cámara lenta."
  ],
  teens: [
    // 50 retos para 13-17 años
    "Haz tu mejor imitación de un TikToker famoso o un meme viral.",
    "Canta el coro de la canción más de moda (aunque no te la sepas bien).",
    "Lee las instrucciones de un shampoo o caja de cereal con voz de tráiler de película.",
    "Haz un 'unboxing' dramático de un objeto cualquiera que tengas cerca.",
    "Intenta hacer el paso de baile 'floss' o 'dab'.",
    "Crea un hashtag para la situación actual del juego.",
    "Explica las reglas de un videojuego a alguien que no sabe nada, pero en menos de 20 segundos.",
    "Haz una pose de superhéroe cada vez que alguien diga tu nombre hasta tu próximo turno.",
    "Actúa como si fueras el presentador de un programa de concursos.",
    "Habla con acento de otro país hasta tu próximo turno.",
    "Propón una nueva regla para el juego que dure una ronda completa.",
    "Haz una reseña súper seria y profesional sobre el vaso de agua que tienes más cerca.",
    "Camina por la habitación como un zombi.",
    "Intenta hacer una 'ola' tú solo.",
    "Haz 15 abdominales.",
    "Intenta nombrar una película por cada letra de tu nombre.",
    "Describe tu serie favorita usando solo 3 palabras.",
    "Ponte de pie y siéntate 10 veces sin usar las manos.",
    "Mantén una plancha por 20 segundos.",
    "Haz un tutorial de maquillaje imaginario usando tus dedos.",
    "Inventa un 'life hack' inútil y explícalo con mucha seriedad.",
    "Intenta decir 'parangaricutirimicuaro' sin equivocarte.",
    "Haz beatbox por 15 segundos.",
    "Elige a un jugador y trata de hacerlo reír sin tocarlo.",
    "Actúa como si fueras el villano de una película explicando tu plan malvado.",
    "Nombra 5 marcas de tenis en 10 segundos.",
    "Haz una reverencia dramática a cada jugador.",
    "Corre en tu lugar levantando mucho las rodillas por 20 segundos.",
    "Crea un 'apodo' para cada jugador.",
    "Haz la voz de un personaje de GPS dando indicaciones para llegar al baño.",
    "Intenta tocar tu nariz con la lengua.",
    "Actúa como si fueras el protagonista de un video musical.",
    "Haz como si fueras un influencer grabando una historia.",
    "Haz tu mejor intento de un 'moonwalk'.",
    "Haz una lista de 3 cosas que te llevarías a una isla desierta.",
    "Habla en tercera persona hasta tu próximo turno (ej. 'Carlos va a tirar el dado').",
    "Haz un apretón de manos secreto con la persona de enfrente.",
    "Intenta adivinar la canción que otro jugador está tarareando.",
    "Haz el mayor tiempo posible diciendo 'ahhhhhhhhh' sin respirar.",
    "Actúa como un gato que derriba un vaso de una mesa.",
    "Da 10 saltos de estrella.",
    "Describe un color sin usar su nombre.",
    "Haz un baile de celebración como si hubieras ganado la lotería.",
    "Intenta ponerte un zapato sin usar las manos.",
    "Conviértete en el 'guardaespaldas' de otro jugador hasta tu próximo turno.",
    "Haz tu mejor grito de batalla.",
    "Intenta hacer que tu estómago ruja a propósito.",
    "Da un discurso inspirador sobre por qué tu color favorito es el mejor.",
    "Haz mímica de una actividad cotidiana (lavarse los dientes, cocinar).",
    "Intenta mantener una cara seria mientras todos los demás intentan hacerte reír por 15 segundos."
  ],
  adults: [
    // 50 retos para 18+ años
    "Actúa como un presentador de noticias dando una noticia ridícula.",
    "Describe tu día de trabajo usando solo mímica.",
    "Haz una imitación de un personaje de una serie o película de los 90.",
    "Inventa un eslogan publicitario para un objeto de la cocina.",
    "Baila como lo hacías en las fiestas cuando tenías 15 años.",
    "Haz una llamada telefónica imaginaria a tu 'yo' de hace 10 años para darle un consejo.",
    "Haz 20 sentadillas.",
    "Elige un jugador y adivina su 'placer culposo' (comida, película, canción).",
    "Intenta escribir tu nombre en el aire con el pie.",
    "Mantén una plancha por 30 segundos.",
    "Canta una canción infantil con la voz más grave que puedas.",
    "Explica algo muy complicado pero sin tener ni idea, usando palabras inventadas.",
    "Haz el sonido de un módem de internet de los 90 conectándose.",
    "Intenta balancear una cuchara sobre tu nariz por 5 segundos.",
    "Da un pequeño discurso de agradecimiento como si hubieras ganado un Óscar.",
    "Haz el sonido de notificación de 3 apps diferentes.",
    "Vuelve a contar la trama de la última película que viste, pero en 30 segundos.",
    "Haz la mayor cantidad de lagartijas (push-ups) que puedas en 20 segundos.",
    "Describe el sabor de la sal sin usar la palabra 'salado'.",
    "Actúa como un agente secreto recibiendo una misión a través de tu zapato.",
    "Nombra 3 cosas que estuvieran de moda cuando ibas en la secundaria.",
    "Paga una penitencia: hazle un cumplido sincero a cada jugador.",
    "Camina por la habitación con un libro en la cabeza sin que se caiga.",
    "Haz un 'review' de la silla en la que estás sentado como si fueras un catador de vinos.",
    "Canta el coro de la primera canción que se te venga a la mente.",
    "Haz 30 segundos de 'escaladores' (mountain climbers).",
    "Lee en voz alta la política de privacidad de un producto cercano con voz dramática.",
    "Habla en rima hasta tu próximo turno.",
    "Haz una imitación de algún familiar.",
    "Intenta nombrar 5 capitales de países en 15 segundos.",
    "Crea un 'cóctel' imaginario con ingredientes ridículos y descríbelo.",
    "Haz la 'postura del árbol' de yoga por 20 segundos.",
    "Actúa como si fueras un extraterrestre descubriendo un tenedor por primera vez.",
    "Defiende una opinión impopular (ej. 'la pizza con piña es la mejor').",
    "Haz una promesa ridícula que (no) cumplirás si ganas el juego.",
    "Habla con un vocabulario excesivamente formal y elegante hasta tu próximo turno.",
    "Intenta tocarte la punta de la nariz con la lengua.",
    "Haz como si fueras un arqueólogo descubriendo un artefacto increíble (un control remoto).",
    "Crea un nuevo signo del zodiaco y describe sus características.",
    "Llora de forma dramática y falsa por algo trivial (como que se acabó el hielo).",
    "Corre en tu lugar por 30 segundos.",
    "Intenta nombrar a los siete enanitos.",
    "Describe el argumento de una película famosa pero de forma terrible.",
    "Haz tu mejor personificación de alguien bostezando contagiosamente.",
    "Conviértete en el narrador de la vida de otro jugador hasta tu próximo turno.",
    "Salta en un pie 15 veces.",
    "Actúa como si fueras el anfitrión de un programa de cocina.",
    "Inventa una teoría de conspiración ridícula sobre los calcetines perdidos.",
    "Elige a un jugador y ten una competencia de miradas. El primero que parpadee o se ría, pierde.",
    "Da tres vueltas sobre ti mismo y luego intenta caminar en línea recta."
  ]
};
